export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';

export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';

export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';

export const SET_NODE_EDITING = 'SET_NODE_EDITING';

export const PUSH_TO_HISTORY = 'PUSH_TO_HISTORY';

export const PUSH_TO_UNDO = 'PUSH_TO_UNDO';

export const REMOVE_UNDO_NODE = 'REMOVE_UNDO_NODE';

export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';

export const UPDATE_CATEGORY_FAILURE = 'UPDATE_CATEGORY_FAILURE';

export const UPDATE_CATEGORY_REQUEST = 'UPDATE_CATEGORY_REQUEST';

export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';

export const ADD_CATEGORY_FAILURE = 'ADD_CATEGORY_FAILURE';

export const ADD_CATEGORY_REQUEST = 'ADD_CATEGORY_REQUEST';

export const RESET_FAKE_DELETING = 'RESET_FAKE_DELETING';

export const RESET_UN_DELETING = 'RESET_UN_DELETING';

export const RESET_DELETING = 'RESET_DELETING';

export const REST_ADDING = 'REST_ADDING';

export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';

export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';

export const DELETE_CATEGORY_FAILURE = 'DELETE_CATEGORY_FAILURE';

