export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";

export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";

export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";

export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';

export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';

export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';

// export const GET_PRODUCT_REQUEST = 'GET_PRODUCTS_REQUEST';
//
// export const GET_PRODUCT_SUCCESS = 'GET_PRODUCTS_SUCCESS';
//
// export const GET_PRODUCT_FAIL = 'GET_PRODUCTS_FAIL';

export const DELETE_PRODUCTS_FILES_REQUEST = 'DELETE_PRODUCTS_FILES_REQUEST';

export const DELETE_PRODUCTS_FILES_SUCCESS = 'DELETE_PRODUCTS_FILES_SUCCESS';

export const DELETE_PRODUCTS_FILES_FAIL = 'DELETE_PRODUCTS_FILES_FAIL';

export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';

export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL';

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';

export const UPDATE_PRODUCT_DESCRIPTION_REQUEST = 'UPDATE_PRODUCT_DESCRIPTION_REQUEST';

export const DELETE_DESCRIPTION_FILES_SUCCESS = 'DELETE_DESCRIPTION_FILES_SUCCESS';

export const DELETE_DESCRIPTION_FILES_FAIL = 'DELETE_DESCRIPTION_FILES_FAIL';

export const DELETE_DESCRIPTION_FILES_REQUEST = 'DELETE_DESCRIPTION_FILES_REQUEST';

export const UPLOAD_PRODUCT_DESCRIPTION_IMAGES_SUCCESS= 'UPLOAD_PRODUCT_DESCRIPTION_IMAGES_SUCCESS';

export const UPLOAD_PRODUCT_DESCRIPTION_IMAGES_FAIL= 'UPLOAD_PRODUCT_DESCRIPTION_IMAGES_FAIL';

export const DELETE_PRODUCT_DESCRIPTION_IMAGES_SUCCESS= 'DELETE_PRODUCT_DESCRIPTION_IMAGES_SUCCESS';

export const DELETE_PRODUCT_DESCRIPTION_IMAGES_FAIL= 'DELETE_PRODUCT_DESCRIPTION_IMAGES_FAIL';

export const UPLOAD_PRODUCT_FILES_SUCCESS = 'UPLOAD_PRODUCT_FILES_SUCCESS';

export const UPLOAD_PRODUCT_FILES_FAIL = 'UPLOAD_PRODUCT_FILES_FAIL';


export const SET_DESCRIPTION = "SET_DESCRIPTION";

export const APPEND_FILE = "APPEND_FILE";

export const REMOVE_FILE = "REMOVE_FILE";
