export const ADD_PRODUCT_FAILURE = "ADD_PRODUCT_FAILURE";

export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";

export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";

export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';

export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';

export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';

// export const GET_PRODUCT_REQUEST = 'GET_PRODUCTS_REQUEST';
//
// export const GET_PRODUCT_SUCCESS = 'GET_PRODUCTS_SUCCESS';
//
// export const GET_PRODUCT_FAILURE = 'GET_PRODUCTS_FAILURE';

export const DELETE_PRODUCTS_FILES_REQUEST = 'DELETE_PRODUCTS_FILES_REQUEST';

export const DELETE_PRODUCTS_FILES_SUCCESS = 'DELETE_PRODUCTS_FILES_SUCCESS';

export const DELETE_PRODUCTS_FILES_FAILURE = 'DELETE_PRODUCTS_FILES_FAILURE';

export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';

export const UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_FAILURE';

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';

export const UPDATE_PRODUCT_DESCRIPTION_REQUEST = 'UPDATE_PRODUCT_DESCRIPTION_REQUEST';

export const DELETE_DESCRIPTION_FILES_FAILURE = 'DELETE_DESCRIPTION_FILES_FAILURE';

export const DELETE_DESCRIPTION_FILES_REQUEST = 'DELETE_DESCRIPTION_FILES_REQUEST';


export const SET_DESCRIPTION = "SET_DESCRIPTION";

export const SET_FILES = "SET_FILES";